default: &default
  title: 云 吧
  host: localhost:3000

  mailer:
    # For localhost postfix
    smtp_settings:
      address: localhost
      port: 25
      enable_starttls_auto: false
      #domain:
      #user_name:
      #password:
      #authentication:
    default_options:
      from: no-reply@example.com
    default_url_options:
      host: localhost:3000


  elasticsearch:
    host: localhost:9200

development:
  <<: *default
  admin_emails:
    - admin@example.com

test:
  <<: *default
  admin_emails:
    - admin@example.com

production:
  <<: *default

  admin_emails:
    - jyootg@gmail.com
